name: Build and Publish ClintonCAT

on:
  push:
    tags:
      - 'v*'
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Package Extension
        run: zip -r clintoncat-extension.zip dist/*

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: clintoncat-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CLINTONCAT_PAT }}
